### ISSUE TITLE
Image Parsing no longer works

### ISSUE THREAD

**Issue by tmunsch** [parkervcp/parkertron#26]
I've tried several times to get the pterodactyl bot and my bot to respond to the text "restart wings" on a white background with black text and it doesn't seem to retrieve the text for some reason even though it's crystal clear.

**Comment by parkervcp** [comment]
Without an example of what you are trying to read I can't test anything. Considering parkertron runs the pterodactyl support bot and it's parsing images there just fine.

**Comment by tmunsch** [comment]
![F6DDBE81-FC79-4CB3-959A-C653DC515CAD](https://user-images.githubusercontent.com/27962004/100104617-6efa3300-2e34-11eb-90f4-87828cf4b302.jpeg)

Here is the test I did last night. The bot responds only when the text is typed not when the image is posted.

**Comment by parkervcp** [comment]
have you ran the bot in debug mode and seen what it thinks that says?

**Comment by PadowYT2** [comment]
Same here, debug is enabled, no logs are seen, just `Reading from`

**Comment by PadowYT2** [comment]
@parkervcp?

**Comment by parkervcp** [comment]
> @parkervcp?

It's 2 years later. If your having issues please post a new issue.
