### ISSUE TITLE
Issuing a response 

### ISSUE THREAD

**Issue by leon12171** [parkervcp/parkertron#28]
Hello, I'm new to your bot. I would like to know from you how to make the bot send a response when a certain image is received?
If possible, then for more details please

**Comment by leon12171** [comment]
![IMG_20201219_081327](https://user-images.githubusercontent.com/24985843/102682446-297e1b00-41d2-11eb-9a0b-b69bb3769d4d.jpg)

**Comment by parkervcp** [comment]
This is not really useful. That looks like it tried to send an empty message. Which it shouldn't do as I specifically cancel all messages that are equal to `""`.
