### ISSUE TITLE
Says "No route to host" is a permissions error.

### ISSUE THREAD

**Issue by JohnB17** [parkervcp/parkertron#29]
When someone sends a mysql error that states "No route to host" the bot responds with saying it is a permissions error, this is a dns error.

**Comment by parkervcp** [comment]
I need examples as to what you are trying to do here.

**Comment by JohnB17** [comment]
This is the image that is inputted:
![image](https://user-images.githubusercontent.com/63297273/110677480-36902200-81a3-11eb-8793-55268e5c5a46.png)

This is what the bot says:
![image](https://user-images.githubusercontent.com/63297273/110677547-4871c500-81a3-11eb-9742-16eb52e1993c.png)

No route to host is a dns error, not mysql permissions error.

**Comment by parkervcp** [comment]
This is not parkertron issue. It sees the select 1 from dual. That's a permissions error.
