### ISSUE TITLE
How

### ISSUE THREAD

**Issue by Rezanans-wow** [parkervcp/parkertron#31]
How i can use embed messages?
Like it 
`{"title":"Как войти в FTP?","description":"Для входа в FTP, перейдите во вкладку `Settings`\n- После вы увидите выделенное окошечко, где написано **SFTP Details**,\n  Это и есть данные для входа.\n\n**Как и почему?**\nServer Address - Это IP или хост для подключения\nUsername - Пользователь или юзер\nLaunch SFTP (Кнопка) - Если ваш клиент поддерживает это, у вас автоматически откроется SFTP клиент с введенными данными кроме пароля\n\n`Где пароль?` \nВаш пароль SFTP есть паролем, который вы используете для доступа к панели управление сервером ","color":1686623,"footer":{"text":"pterohost.com - SFTP (Game)"}}`

**Comment by parkervcp** [comment]
Embeds are not actually implemented as of yet.
