### ISSUE TITLE
BOT reply to user's message (method)

### ISSUE THREAD

**Issue by mrc4tt** [parkervcp/parkertron#38]
Hi.

Is it possible for BOT to use the "Reply" method, the same as possible to use on discord?

Before:
![](https://pic.lindhost.eu/DPPR1bFxlN.png)

For example (like this, where I reply directly to BOT's message)
![](https://pic.lindhost.eu/8pN1lTGDXZ.png)

**Comment by parkervcp** [comment]
I have plans to use reply instead I have not gotten to it.

**Comment by mrc4tt** [comment]
Any update about this? ^^
