### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ItJustFox** [parkervcp/parkertron#43]
Hello sorry for maybe the _*stupid*_ question but is it possible to have mutilple keyword and regex I have try some thing but hmm nothing same to work is there a specifique way to do it ? ^^'

**Comment by ItJustFox** [comment]
Btw, is possible to make the Bot run with the same commands & CONFIG for two server ?

**Comment by parkervcp** [comment]
I hadn't even gotten to looking at this. The default config that is generated is multiple matches for keywords. The regex config should be similar.
