### ISSUE TITLE
Parkertron doesn't read images

### ISSUE THREAD

**Issue by PadowYT2** [parkervcp/parkertron#45]
## The issue

When I post an image to Discord, like
![https://media.discordapp.net/attachments/898588635090288711/1015527702448586772/unknown.png](https://media.discordapp.net/attachments/898588635090288711/1015527702448586772/unknown.png)

It reacts, send message to logs, but no errors, no response

## Some more info

> [Server log](https://haste.padow.ru/raw/ilalaketem)
> [Full startup log](https://haste.padow.ru/raw/umilinukih)
> Similar issue: #26

**Comment by parkervcp** [comment]
Please run the bot in debug mode.

**Comment by PadowYT2** [comment]
I did with `-v debug`

**Comment by parkervcp** [comment]
There should be more after the link to the image.

**Comment by PadowYT2** [comment]
Nope, nothing

**Comment by PadowYT2** [comment]
Look, @parkervcp, I'm going on a vacantion soon, as I provided the Full Server log, you can look in that, and no, the bot doesn't stop sending stuff in console (like another `Reading from`). Maybe there's an another way to start with debug?
