### ISSUE TITLE
Channel errorstate

### ISSUE THREAD

**Issue by hypersmc** [parkervcp/parkertron#50]
error: FATA[0009] Channel errorstate cache not found
When: Whenever I try to DM the bot it crashes and gives that error
logs: https://bin.zennodes.dk/k1PO2-9psrw/raw (with debug mode)

Also its the newest version as its installed today

**Comment by parkervcp** [comment]
Do you have a config you can share for the bot?

**Comment by hypersmc** [comment]
> Do you have a config you can share for the bot?

yes:
bot.yml: https://bin.zennodes.dk/1MfcH-Bb8OB-UxVF4-mQL5m-QGEsZ-5UCU9-cRvUIF1fn2
server.yml: https://bin.zennodes.dk/wu9hO-L4hX5-PJS9B-jGszG-aBDFA-5isA0-SyVAQXoGZ7
