### ISSUE TITLE
image.DecodeConfig fails

### ISSUE THREAD

**Issue by lionkor** [parkervcp/parkertron#62]
Hi,

in `getImageDimension` in `discord.go` the call 

```go
	image, _, err := image.DecodeConfig(file)
```
fails because the following imports are missing at the top of the file:
```go
	_ "image/png"
	_ "image/jpeg"
```

Adding these solves the problem.

I encountered this on my fork of parkertron, on `master` and I tested it without my commits. I'm pretty sure the current master here also has this issue. To reproduce, simply post an image and the bot will crash.

**Comment by lionkor** [comment]
See https://github.com/parkervcp/parkertron/commit/cbb8b6acf779bb39ad9b3da951f5a79c72dbead1

**Comment by parkervcp** [comment]
resolved by https://github.com/parkervcp/parkertron/pull/63

**Comment by parkervcp** [comment]
Your fix is better than mine was so I am implementing it.

**Comment by lionkor** [comment]
No idea if it would still crash if it encounters an unknown codec? Maybe an error check is still a good idea down the line anyways ;)

thanks!

**Comment by lionkor** [comment]
Ah nevermind, you did! Perfect.
