### ISSUE TITLE
Egg for AAPG

### ISSUE THREAD

**Issue by Notsomomma** [parkervcp/parkertron#71]
Hello, I've been sent to you by a couple of people in regards to making a egg for Petrodycle platform for american army proving gound.

here is all the links and info you would need. Please let me know if you're able or not able to create an egg. 

Thanks in advance

https://steamcommunity.com/app/203290/discussions/6/846963165509522965/  docs

https://store.steampowered.com/app/203290/Americas_Army_Proving_Grounds/ steam game

https://www.americasarmy.com/ to the software

**Comment by parkervcp** [comment]
This is not related to the bot
